/* SPDX-License-Identifier: MIT */
/*
 * Copyright (c) 2026 Carlos López <carlos.lopezr4096@gmail.com>
 *
 * pcref: scalable reference counting on top of librseq.
 *
 * pcref is a userspace reimplementation of a subset of the Linux
 * kernel's percpu_ref. No code is directly pulled from the kernel.
 *
 * USAGE:
 *
 * pcref_init() creates the object with 1 reference, held by the owner.
 * Other users can take references with pcref_get(), pcref_tryget() or
 * pcref_tryget_live(). References are dropped with pcref_put().
 *
 * The owner's initial reference must be dropped with pcref_kill() or
 * pcref_kill_and_confirm(), after which point pcref_tryget_live() will
 * start failing. The caller may be notified once the object is marked
 * as dying by using pcref_kill_and_confirm(). Before calling
 * pcref_kill(), pcref_put() does not check for the refcount hitting 0.
 *
 * Note that you may create specific helpers for your type using
 * PCREF_DEFINE().
 */
#ifndef PCREF_H
#define PCREF_H

#include "pcref_internal.h"

/*
 * @flags for pcref_init().
 */
enum pcref_init_flags {
	/*
	 * Start (and, since we never switch back, remain) in atomic mode
	 * with a refcount of 1.
	 */
	PCREF_INIT_ATOMIC = 1u << 0,
};

#if defined(__GNUC__)
#define PCREF_MUST_CHECK __attribute__((warn_unused_result))
#else
#define PCREF_MUST_CHECK
#endif

/*
 * Initialize @ref with one reference owned by the caller. @release is
 * invoked (with @ref) when the last reference is dropped; it typically
 * frees the containing object and must call pcref_exit().
 *
 * Starts in per-CPU mode unless PCREF_INIT_ATOMIC is set in @flags.
 * Returns 0 on success or a negative errno on error..
 */
PCREF_MUST_CHECK int pcref_init(struct pcref *ref, pcref_func_t release,
								unsigned int flags);

/*
 * Undo pcref_init().
 *
 * The caller is responsible for ensuring that @ref is no longer in use.
 * This may be called from the release callback.
 *
 * The autogenerated destructor for PCREF_DEFINE() already calls this
 * function before invoking the user-defined callback.
 */
void pcref_exit(struct pcref *ref);

/*
 * Drop the initial reference and mark @ref as dying so that further
 * calls to pcref_tryget_live() will fail. This converts the object to
 * atomic mode first. Must be called **exactly once** per pcref.
 *
 * Once the object is dead from every thread's point of view, @confirm
 * is invoked. At this point, further pcref_tryget_live() calls are
 * guaranteed to fail. @confirm must not block.
 */
void pcref_kill_and_confirm(struct pcref *ref, pcref_func_t confirm);

/*
 * Like pcref_kill_and_confirm(), but it does not invoke any
 * confirmation callback.
 */
static inline void pcref_kill(struct pcref *ref)
{
	pcref_kill_and_confirm(ref, NULL);
}

/*
 * Convert a per-CPU object to atomic mode without dropping a reference
 * The caller must hold a reference. Idempotent and thread-safe; there
 * is no way back to per-CPU mode.
 *
 * You generally want to use pcref_kill() or pcref_kill_and_confirm()
 * instead, which drops the owner's reference.
 *
 * This allows you to use pcref_is_zero() reliably, as it will always
 * return false when in per-CPU mode, since the reference count is
 * guaranteed to not be zero before switching to atomic mode.
 *
 * If @confirm is non-NULL it is invoked with @ref, exactly once per
 * call, once per-CPU updates can no longer happen.
 *
 * Note! If another thread is performing the switch, this call does
 * **not** wait for it to complete. You can spin in your callback until
 * pcref_is_atomic() returns true if you want blocking behavior.
 * Until then, the actual refcount is guaranteed to be non-zero, but
 * will not be reliable.
 */
void pcref_switch_to_atomic(struct pcref *ref, pcref_func_t confirm);

/*
 * Returns true if the refcount has reached zero. This function is
 * always safe to call after pcref_init() and before pcref_exit().
 */
static inline bool pcref_is_zero(const struct pcref *ref)
{
	if (atomic_load_acquire(&ref->mode) != PCREF_MODE_ATOMIC)
		return false;
	/* Acquire pairs with the acq_rel decrements of previous holders */
	return atomic_load_acquire(&ref->count) == 0;
}

/* Returns true if @ref is in per-CPU mode. */
static inline bool pcref_is_percpu(const struct pcref *ref)
{
	return atomic_load_acquire(&ref->mode) == PCREF_MODE_PERCPU;
}

/* Returns true if @ref is in atomic mode */
static inline bool pcref_is_atomic(const struct pcref *ref)
{
	return atomic_load_acquire(&ref->mode) == PCREF_MODE_ATOMIC;
}

/*
 * Returns true if @ref is dying or dead. Always safe to call after
 * pcref_init() and before pcref_exit().
 */
static inline bool pcref_is_dying(const struct pcref *ref)
{
	return atomic_load_acquire(&ref->dying);
}

/*
 * Acquire @nr references for @ref. The caller must already hold a
 * reference.
 */
static inline void pcref_get_many(struct pcref *ref, unsigned long nr)
{
	if (!__pcref_percpu_add(ref, (intptr_t)nr))
		atomic_fetch_add_relaxed(&ref->count, (intptr_t)nr);
}

/*
 * Acquire a reference for @ref. The caller must already hold a
 * reference.
 */
static inline void pcref_get(struct pcref *ref)
{
	pcref_get_many(ref, 1);
}

/* Drop @nr references for @ref */
static inline void pcref_put_many(struct pcref *ref, unsigned long nr)
{
	if (!__pcref_percpu_add(ref, -(intptr_t)nr))
		__pcref_atomic_put(ref, nr);
}

static inline void pcref_put(struct pcref *ref)
{
	pcref_put_many(ref, 1);
}

/*
 * Take @nr references only if the object has not already dropped to
 * 0. Use this when you hold a pointer but not a reference (e.g. when
 * retrieving it from a lookup table).
 */
static inline bool pcref_tryget_many(struct pcref *ref,
									 unsigned long nr)
{
	return __pcref_tryget(ref, nr, memory_order_acquire);
}

/*
 * Take a reference for @ref if the reference count has not already
 * dropped to 0. Use this when you hold a pointer but not a reference
 * (e.g. when retrieving it from a lookup table).
 */
static inline bool pcref_tryget(struct pcref *ref)
{
	return pcref_tryget_many(ref, 1);
}

/*
 * Like pcref_tryget() but also fails once pcref_kill() has been called
 * (that is, if the owner's reference has been dropped).
 */
static inline bool pcref_tryget_live(struct pcref *ref)
{
	if (pcref_is_dying(ref))
		return false;

	/*
	 * The kill may have completed between the check above and taking
	 * the reference. Recheck after taking it, so that a successful
	 * return is ordered before pcref_kill_and_confirm()'s confirmation.
	 *
	 * Per-CPU updates are ordered against kill by its membarrier.
	 * Atomic updates need the increment ordered before the load of
	 * ->dying (a store->load edge), so both the increment and the load
	 * are seq_cst, pairing with the seq_cst store of ->dying in the
	 * kill.
	 */
	if (!__pcref_tryget(ref, 1, memory_order_seq_cst))
		return false;
	if (rseq_unlikely(atomic_load(&ref->dying))) {
		/* We hold a reference, so this put is the normal release path
		 */
		pcref_put(ref);
		return false;
	}

	return true;
}

/*
 * PCREF_DEFINE(prefix, type, member, destroy)
 *
 * Generates a typed API for a refcounted object type:
 *
 *     struct foo { struct pcref ref; ... };
 *     static void foo_destroy(struct foo *f) { free(f); }
 *     PCREF_DEFINE(foo, struct foo, ref, foo_destroy)
 *
 *     foo_ref_init(f, flags);   foo_get(f);        foo_put(f);
 *     foo_tryget(f);            foo_tryget_live(f);
 *     foo_kill(f);              foo_switch_to_atomic(f);
 *
 * @destroy is called as destroy(type *) when the last reference goes
 * away; the generated release callback calls pcref_exit() (to free the
 * per-cid cells) before @destroy, so @destroy is free to free the
 * embedding object.
 */
#define PCREF_DEFINE(prefix, type, member, destroy)              \
	static inline void prefix##__release(struct pcref *r)        \
	{                                                            \
		type *o = pcref_container_of(r, type, member);           \
		pcref_exit(r);                                           \
		destroy(o);                                              \
	}                                                            \
	PCREF_MUST_CHECK static inline int prefix##_ref_init(        \
			type *o, unsigned int flags)                         \
	{                                                            \
		return pcref_init(&o->member, prefix##__release, flags); \
	}                                                            \
	static inline type *prefix##_get(type *o)                    \
	{                                                            \
		pcref_get(&o->member);                                   \
		return o;                                                \
	}                                                            \
	static inline void prefix##_put(type *o)                     \
	{                                                            \
		pcref_put(&o->member);                                   \
	}                                                            \
	static inline bool prefix##_tryget(type *o)                  \
	{                                                            \
		return pcref_tryget(&o->member);                         \
	}                                                            \
	static inline bool prefix##_tryget_live(type *o)             \
	{                                                            \
		return pcref_tryget_live(&o->member);                    \
	}                                                            \
	static inline void prefix##_kill(type *o)                    \
	{                                                            \
		pcref_kill(&o->member);                                  \
	}                                                            \
	static inline void prefix##_switch_to_atomic(type *o)        \
	{                                                            \
		pcref_switch_to_atomic(&o->member, NULL);                \
	}

#endif /* PCREF_H */
